# Generated by Django 3.0.2 on 2020-02-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wePost', '0003_auto_20200216_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
