# Generated by Django 3.0.3 on 2020-02-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wePost', '0005_auto_20200216_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Accepted')], default='U', max_length=1),
        ),
    ]
