# Generated by Django 3.0.3 on 2020-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wePost', '0005_auto_20200216_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'plain text'), ('text/markdown', 'markdown text')], default='text/markdown', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'plain text'), ('text/markdown', 'markdown text')], default='text/markdown', max_length=16),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://127.0.0.1:3000/'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://127.0.0.1:3000/'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Accepted')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='port',
            field=models.IntegerField(blank=True, default=3000),
        ),
    ]
