# Generated by Django 3.0.3 on 2020-02-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wePost', '0006_auto_20200219_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='active',
        ),
        migrations.AlterField(
            model_name='author',
            name='registerStatus',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('A', 'Allowed')], default='U', max_length=1),
        ),
    ]
