# Generated by Django 3.0.3 on 2020-02-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wePost', '0006_auto_20200216_2033'),
        ('wePost', '0007_auto_20200219_1220'),
    ]

    operations = [
    ]
